# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveHeader',
            fields=[
                ('headerType', models.CharField(max_length=100000, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
