# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorOutput',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue')], default='green', max_length=10)),
            ],
        ),
    ]
