# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_remove_coloroutput_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloroutput',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=10),
        ),
    ]
