# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_coloroutput_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100000)),
            ],
        ),
    ]
